/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfazGrafica.Admin;

import Objetos.Categoria.Categoria;
import Objetos.Categoria.ListaCategorias;
import Objetos.Producto.ListaProductos;
import Objetos.Producto.Producto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lobje
 */
public class AdminProducto extends javax.swing.JPanel {

    ListaCategorias categorias;
    private String nombre;
    private String precioTxt;
    private String cantidadTxt;
    
    private double precio;
    private int cantidad;
    /* VARIABLE USADA PARA MOSTRAR EL NUMERO DE PRODUCTOS REGISTRADOS*/
    private int No_;
    
    DefaultTableModel modelo;
    /**
     * Creates new form AdminProducto
     */
    public AdminProducto() {
        initComponents();
    }
    
    public void setListas(ListaCategorias categorias){
        this.categorias = categorias;
        llegarOpcionCategoria();
        llenarTabla();
    }     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        opcionCat = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProductos = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Registrar producto");

        jLabel2.setText("Nombre");

        jLabel3.setText("Precio");

        jLabel4.setText("Cantidad");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        opcionCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Categoria");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCantidad)
                            .addComponent(txtPrecio)
                            .addComponent(txtNombre)
                            .addComponent(opcionCat, 0, 102, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnAceptar)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(96, 96, 96))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcionCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(53, 53, 53)
                .addComponent(btnAceptar)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        tableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane1.setViewportView(tableProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        
        registra();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void registra(){
        if(camposLlenos()){
            if(isCantidad()){
                if(isPrecio()){
                        int result = this.categorias.registroProduct(this.opcionCat.getSelectedItem().toString(), nombre, precio, cantidad);
                        
                        switch (result) {
                            case 1:
                                mensaje("Registrado"); 
                                break;
                            case 2:
                                mensaje("La cantidad debe ser mayor a cero");
                                break;
                            case 3:
                                mensaje("El precio debe ser mayor a cero");
                                break;
                            case 4:
                                mensaje("El producto "+nombre+" ya existe");
                                break;
                        }
                        llenarTabla();
                }
            }
        }
    }
    
    private boolean camposLlenos()
    {
        String msj = "";
        this.nombre = this.txtNombre.getText();
        this.cantidadTxt = this.txtCantidad.getText();
        this.precioTxt = this.txtPrecio.getText();
        
        if(nombre.equals("")) msj += "Codigo obligatorio\n";
        if(cantidadTxt.equals("")) msj += "Cantida obligatorio\n";
        if(precioTxt.equals("")) msj += "Precio obligatorio\n";
        if(!msj.equals("")){
            mensaje(msj);
            return false;
        }
        return true;
    }
    
    private boolean isCantidad(){
        try {
            cantidad = Integer.parseInt(cantidadTxt);
            return true;
        } catch (Exception e) {
            mensaje("La cantidad debe ser un numero entero");
            return false;
        }
    }
    
    private boolean isPrecio(){
        try {
            precio = Double.parseDouble(precioTxt);
            return true;
        } catch (Exception e) {
            mensaje("La precio debe ser un numero entero o con punto decimal");
            return false;
        }
    }
    
    public void llegarOpcionCategoria(){
        this.opcionCat.removeAllItems();
        int cantidad = this.categorias.cantidad();
        for (int i = 0; i < cantidad; i++) {
            this.opcionCat.addItem(this.categorias.getCategoria(i).getNombre());
        }
    }
    
    /* ******************************************************************************************************************
     * ******************************************************************************************************************
     * ****************************************************************************************************************** */
    
    public void llenarTabla(){
        this.modelo = new DefaultTableModel();
        modelo.addColumn("No.");
        modelo.addColumn("Nombre");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");
        modelo.addColumn("Categoria");
                
        int cantidad = this.categorias.cantidad();
        No_ = 0;
        Categoria tmp;
        for (int i = 0; i < cantidad; i++) {
            tmp = this.categorias.getCategoria(i);
            //addRowTable(i, codigo, porc);
            //addRowTable(i, tmp.getNombre(), tmp.getProductos().Cantidad());
            llenarTablaPorCategoria(tmp.getProductos(), tmp.getNombre());
        }
        
        this.tableProductos.setModel(modelo);
        this.tableProductos.getColumnModel().getColumn(0).setMaxWidth(30);
    }
    
    
    public void llenarTablaPorCategoria(ListaProductos productos, String categoria){
                
        int cantidad = productos.Cantidad();
        Producto tmp;
        for (int i = 0; i < cantidad; i++) {
            tmp = productos.Obtener(i);
            //addRowTable(i, codigo, porc);
            No_++;
            addRowTable(No_, tmp.getNombre(), tmp.getCantidad(), tmp.getPrecio(), categoria);
        }
    }
    
    private void addRowTable(int id, String nombre, int cantidad, double precio, String categoria){
        modelo.addRow(new Object[]{String.valueOf(id), nombre, String.valueOf(cantidad), String.valueOf(precio), categoria});
        this.tableProductos.setModel(modelo);
    }
    
    /* ******************************************************************************************************************
     * ******************************************************************************************************************
     * ****************************************************************************************************************** */
    private void mensaje(String mensaje){
        JOptionPane.showMessageDialog(null, mensaje);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> opcionCat;
    private javax.swing.JTable tableProductos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
