/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica.ventas;

import InterfazGrafica.Admin.AdminCategoria;
import InterfazGrafica.Admin.AdminCupon;
import InterfazGrafica.Admin.AdminProducto;
import Objetos.Categoria.ListaCategorias;
import Objetos.Cupon.ListaCupones;
import Objetos.Usuarios.ListUser;

/**
 *
 * @author lobje
 */
public class Administrador extends javax.swing.JFrame {

    AdminCategoria panelCategoria;
    AdminCupon panelCupon;
    AdminProducto panelProductos;
    
    ListaCupones cupones;
    ListaCategorias categorias;
    ListUser usuarios;
    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
    }
    
    public void setListas(ListaCategorias categorias, ListaCupones cupones, ListUser usuarios){
        this.categorias = categorias;
        this.cupones = cupones;
        this.usuarios = usuarios;
        addPanels();
    }
    
    private void addPanels(){
        this.panelCupon = new AdminCupon();
        this.panelCupon.setListas(this.cupones);
        this.panelCupon.setVisible(true);
        this.panelCupon.setSize(670, 350);
        
        this.panelCategoria = new AdminCategoria();
        this.panelCategoria.setListas(this.categorias);
        this.panelCategoria.setVisible(true);
        this.panelCategoria.setSize(670, 350);
        
        this.panelProductos = new AdminProducto();
        this.panelProductos.setListas(this.categorias);
        this.panelProductos.setVisible(true);
        this.panelProductos.setSize(670, 350);
        
        this.tabAdmin.addTab("Cupones", this.panelCupon);
        this.tabAdmin.addTab("Categorias", this.panelCategoria);
        this.tabAdmin.addTab("Productos", this.panelProductos);
        this.setSize(850, 500);
        //actualizarListas();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabAdmin = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabAdmin.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabAdmin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabAdminStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Administrado");

        btnCerrarSesion.setBackground(new java.awt.Color(255, 0, 0));
        btnCerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrarSesion.setText("Cerrar sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrarSesion)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnCerrarSesion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(tabAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabAdminStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabAdminStateChanged
        // TODO add your handling code here:
        //System.out.println("Aqui");
        actualizarListas();
    }//GEN-LAST:event_tabAdminStateChanged

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    
    /* ******************************************************************************************************************
     * ******************************************************************************************************************
     * ****************************************************************************************************************** */
    private void actualizarListas()
    {
        //this.panelCupon.setListas(this.cupones);
        //this.panelCategoria.setListas(this.categorias);
        //this.panelProductos.setListas(this.categorias);
        this.panelProductos.llegarOpcionCategoria();
        this.panelCategoria.llenarTabla();
    }
    
    private void salir(){
        Login login = new Login();
        login.setListas(categorias, cupones, usuarios);
        login.setVisible(true);
        this.dispose();
    }
    /* ******************************************************************************************************************
     * ******************************************************************************************************************
     * ****************************************************************************************************************** */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane tabAdmin;
    // End of variables declaration//GEN-END:variables

}
