/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import Hilos.MovimientoFicha;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author lobje
 */
public class Ventana extends javax.swing.JFrame {

    int dimension;
    MovimientoFicha mf;
    int fichaX;
    int fichaO;
    boolean tipoFicha;
    int velocidad;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.dimension = 100;
        AddImages();
        this.mf = new MovimientoFicha();
        this.fichaO = 1;
        this.fichaX = 1;
        this.tipoFicha = true;
        this.velocidad = 25;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        O1 = new javax.swing.JLabel();
        O2 = new javax.swing.JLabel();
        O3 = new javax.swing.JLabel();
        O4 = new javax.swing.JLabel();
        O5 = new javax.swing.JLabel();
        X1 = new javax.swing.JLabel();
        X2 = new javax.swing.JLabel();
        X3 = new javax.swing.JLabel();
        X4 = new javax.swing.JLabel();
        X5 = new javax.swing.JLabel();
        btnOp1 = new javax.swing.JButton();
        btnOp2 = new javax.swing.JButton();
        btnOp3 = new javax.swing.JButton();
        btnOp4 = new javax.swing.JButton();
        btnOp5 = new javax.swing.JButton();
        btnOp6 = new javax.swing.JButton();
        btnOp7 = new javax.swing.JButton();
        btnOp8 = new javax.swing.JButton();
        btnOp9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 560));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        O1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/o.jpg"))); // NOI18N
        O1.setPreferredSize(new java.awt.Dimension(100, 100));
        getContentPane().add(O1, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 51, -1, -1));

        O2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/o.jpg"))); // NOI18N
        O2.setPreferredSize(new java.awt.Dimension(100, 100));
        getContentPane().add(O2, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 163, -1, -1));

        O3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/o.jpg"))); // NOI18N
        O3.setPreferredSize(new java.awt.Dimension(100, 100));
        getContentPane().add(O3, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 281, -1, -1));

        O4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/o.jpg"))); // NOI18N
        O4.setPreferredSize(new java.awt.Dimension(100, 100));
        getContentPane().add(O4, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 124, -1, -1));

        O5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/o.jpg"))); // NOI18N
        O5.setPreferredSize(new java.awt.Dimension(100, 100));
        getContentPane().add(O5, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 242, -1, -1));

        X1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/x.jpg"))); // NOI18N
        X1.setPreferredSize(new java.awt.Dimension(100, 100));
        getContentPane().add(X1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 48, -1, -1));

        X2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/x.jpg"))); // NOI18N
        X2.setPreferredSize(new java.awt.Dimension(100, 100));
        getContentPane().add(X2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 166, -1, -1));

        X3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/x.jpg"))); // NOI18N
        X3.setPreferredSize(new java.awt.Dimension(100, 100));
        getContentPane().add(X3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 284, -1, -1));

        X4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/x.jpg"))); // NOI18N
        X4.setPreferredSize(new java.awt.Dimension(100, 100));
        getContentPane().add(X4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 139, -1, -1));

        X5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/x.jpg"))); // NOI18N
        X5.setPreferredSize(new java.awt.Dimension(100, 100));
        getContentPane().add(X5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 245, -1, -1));

        btnOp1.setText("Op 1");
        btnOp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOp1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnOp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 407, -1, -1));

        btnOp2.setText("Op 2");
        btnOp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOp2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnOp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 407, -1, -1));

        btnOp3.setText("Op 3");
        btnOp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOp3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnOp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 407, -1, -1));

        btnOp4.setText("Op 4");
        btnOp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOp4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnOp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 443, -1, -1));

        btnOp5.setText("Op 5");
        btnOp5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOp5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnOp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 443, -1, -1));

        btnOp6.setText("Op 6");
        btnOp6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOp6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnOp6, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 443, -1, -1));

        btnOp7.setText("Op 7");
        btnOp7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOp7ActionPerformed(evt);
            }
        });
        getContentPane().add(btnOp7, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 479, -1, -1));

        btnOp8.setText("Op 8");
        btnOp8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOp8ActionPerformed(evt);
            }
        });
        getContentPane().add(btnOp8, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 479, -1, -1));

        btnOp9.setText("Op 9");
        btnOp9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOp9ActionPerformed(evt);
            }
        });
        getContentPane().add(btnOp9, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 479, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOp1ActionPerformed
        // TODO add your handling code here:
        siguienteFicha(10, 300, 50, 50, velocidad);
    }//GEN-LAST:event_btnOp1ActionPerformed

    private void btnOp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOp2ActionPerformed
        // TODO add your handling code here:
        siguienteFicha(10, 410, 50, 50, velocidad);
    }//GEN-LAST:event_btnOp2ActionPerformed

    private void btnOp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOp3ActionPerformed
        // TODO add your handling code here:
        siguienteFicha(10, 520, 50, 50, velocidad);
    }//GEN-LAST:event_btnOp3ActionPerformed

    private void btnOp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOp4ActionPerformed
        // TODO add your handling code here:
        siguienteFicha(10, 300, 50, 160, velocidad);
    }//GEN-LAST:event_btnOp4ActionPerformed

    private void btnOp5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOp5ActionPerformed
        // TODO add your handling code here:
        siguienteFicha(10, 410, 50, 160, velocidad);
    }//GEN-LAST:event_btnOp5ActionPerformed

    private void btnOp6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOp6ActionPerformed
        // TODO add your handling code here:
        siguienteFicha(10, 520, 50, 160, velocidad);
    }//GEN-LAST:event_btnOp6ActionPerformed

    private void btnOp7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOp7ActionPerformed
        // TODO add your handling code here:
        siguienteFicha(10, 300, 50, 270, velocidad);
    }//GEN-LAST:event_btnOp7ActionPerformed

    private void btnOp8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOp8ActionPerformed
        // TODO add your handling code here:
        siguienteFicha(10, 410, 50, 270, velocidad);
    }//GEN-LAST:event_btnOp8ActionPerformed

    private void btnOp9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOp9ActionPerformed
        // TODO add your handling code here:
        siguienteFicha(10, 520, 50, 270, velocidad);
    }//GEN-LAST:event_btnOp9ActionPerformed
    /* *********************************************************************************************************
     * *********************************************************************************************************
      * ******************************************************************************************************** */
    private void SeleccionarFichaX(int posInicialX, int posFinalX, int posInicialY, int posFinalY, int veocidad){
        JLabel tmp = X1;
        switch (fichaX) {
            case 1:
                tmp = X1;
                break;
            case 2:
                tmp = X2;
                break;
            case 3:
                tmp = X3;
                break;
            case 4:
                tmp = X4;
                break;
            case 5:
                tmp = X5;
                break;
        }
        mf.moverFiccha(tmp, posInicialX, posFinalX, posInicialY, posFinalY, veocidad);
        fichaX++;
    }
    
    private void SeleccionarFichaO(int posInicialX, int posFinalX, int posInicialY, int posFinalY, int veocidad){
        JLabel tmp = O1;
        switch (fichaO) {
            case 1:
                tmp = O1;
                break;
            case 2:
                tmp = O2;
                break;
            case 3:
                tmp = O3;
                break;
            case 4:
                tmp = O4;
                break;
            case 5:
                tmp = O5;
                break;
        }
        mf.moverFiccha(tmp, posInicialX, posFinalX, posInicialY, posFinalY, veocidad);
        fichaO++;
    }
    
    private void siguienteFicha(int posInicialX, int posFinalX, int posInicialY, int posFinalY, int veocidad){
        if(tipoFicha) SeleccionarFichaX(posInicialX, posFinalX, posInicialY, posFinalY, veocidad);
        else SeleccionarFichaO(posInicialX, posFinalX, posInicialY, posFinalY, veocidad);
        this.tipoFicha = !tipoFicha;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    
    /************************************************************************************/
    
    private void AddImages(){
        String pathX = "./src/Images/x.jpg";
        String pathO = "./src/Images/o.jpg";
        
        mostrarImagen(O1, pathO);
        mostrarImagen(O2, pathO);
        mostrarImagen(O3, pathO);
        mostrarImagen(O4, pathO);
        mostrarImagen(O5, pathO);
        mostrarImagen(X1, pathX);
        mostrarImagen(X2, pathX);
        mostrarImagen(X3, pathX);
        mostrarImagen(X4, pathX);
        mostrarImagen(X5, pathX);
    }
    
    private void mostrarImagen(JLabel cuadro, String ruta){
        
        if(!ruta.equals("")){
            Image img = new ImageIcon(ruta).getImage();
            img = img.getScaledInstance(this.dimension, this.dimension   , Image.SCALE_SMOOTH);
            ImageIcon imgI = new ImageIcon(img);
            cuadro.setIcon(imgI);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel O1;
    private javax.swing.JLabel O2;
    private javax.swing.JLabel O3;
    private javax.swing.JLabel O4;
    private javax.swing.JLabel O5;
    private javax.swing.JLabel X1;
    private javax.swing.JLabel X2;
    private javax.swing.JLabel X3;
    private javax.swing.JLabel X4;
    private javax.swing.JLabel X5;
    private javax.swing.JButton btnOp1;
    private javax.swing.JButton btnOp2;
    private javax.swing.JButton btnOp3;
    private javax.swing.JButton btnOp4;
    private javax.swing.JButton btnOp5;
    private javax.swing.JButton btnOp6;
    private javax.swing.JButton btnOp7;
    private javax.swing.JButton btnOp8;
    private javax.swing.JButton btnOp9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
